### PR TITLE
feat(extension): [LW-10494]  Lace migration background script

### PR DESCRIPTION
**Pull request by renanvalentin**
# Checklist

- [x] JIRA -[LW-10494](https://input-output.atlassian.net/browse/LW-10494)
- [x] Proper tests implemented

---

## Proposed solution

**feat(extension): nami migration runner**
It is responsible for migrating the data, it contains a few unit tests covering: 
- fresh install
- lace already installed and has no conflict
- some existing accounts  conflict
- all existing accounts conflict

**feat(extension): migration background service listener**
Exposes the following background script:

- **checkMigrationStatus**:
    -  Invoke this method when the Lace's popup is opened, if the migration status is "In Progress", redirect the user to the migration flow
- **startMigration**:
    -  Invoke this method when starting the migration flow; if successful, it will return the currency preference setting.

### CODE REVIEW

**Comment by DominikGuzei** [comment]
@renanvalentin im running into this error when trying to link the migration tool into my local repo: 
image

**Comment by DominikGuzei** [comment]
nevermind, could resolve it with `npm pack` 👍

**Comment by DominikGuzei** [comment]
@renanvalentin im getting this build error when running `yarn build`:
image

**Comment by renanvalentin** [comment]
@DominikGuzei fixed! good catch

**Review by DominikGuzei — APPROVED** [review]
great work 👏

**Review by VanessaPC — APPROVED** [review]
LGTM!

**Pull request merged**
